apiVersion: v1
kind: Service
metadata:
  name: nodeconsoleapp-service
spec:
  selector:
    app: nodeconsoleapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80          # Port on LoadBalancer (External IP)
      targetPort: 3000  # Port inside the Pod (Node.js app)
